# Generated by Django 4.1.1 on 2022-10-14 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_up1_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='up1',
            name='user',
        ),
        migrations.AddField(
            model_name='up1',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
