# Generated by Django 4.1.1 on 2022-10-14 15:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_up1_user_up1_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='up1',
            name='user',
        ),
        migrations.AddField(
            model_name='up1',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
