# Generated by Django 4.0.5 on 2023-03-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_up1_user_up1_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('C', 'ได้รับคำสั่งซื้อแล้ว'), ('P', 'กำลังบรรจุ'), ('D', 'กำลังจัด'), ('E', 'คำสั่งซื้อถูกยกเลิก')], max_length=1),
        ),
    ]
